=== Alathreon/AlaHexEditor/src/main/resources/alahex.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/Alathreon/AlaHexEditor/refs/heads/master/src/main/resources/alahex.schema.json",
    "title": "AlaHexEditor parse format",
    "type": "object",
    "required": ["references", "endianness", "types", "schema"],
    "properties": {
        "references": {
            "type": "array",
            "items": { "type": "string", "format": "uri" }
        },
        "endianness": {
            "type": "string",
            "enum": ["BIG", "LITTLE"]
        },
        "types": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "\\w+": {
                    "$ref": "#/$defs/SchemaType"
                }
            }
        },
        "schema": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "\\w+": {
                    "$ref": "#/$defs/SchemaElement"
                }
            }
        }
    },
    "$defs": {
        "SchemaType": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["@type", "lengthPolicy"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "BitsetType" },
                        "lengthPolicy": { "$ref": "#/$defs/LengthPolicy" },
                        "names": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "isLengthBits": {
                            "type": "boolean",
                            "default": false
                        }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "size", "constants"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "EnumType" },
                        "size": { "$ref": "#/$defs/ByteSize" },
                        "constants": { "type": "object", "$ref": "#/$defs/Bindings" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "members"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "StructType" },
                        "members": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": {
                                "\\w+": {
                                    "$ref": "#/$defs/SchemaElement"
                                }
                            }
                        }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "classifier"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "UnionType" },
                        "classifier": { "type": "object", "$ref": "#/$defs/Classifier" }
                    }
                }
            ]
        },
        "SchemaElement": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["@type", "variable", "size"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ArrayReferenceElement" },
                        "variable": { "type": "string" },
                        "size": { "$ref": "#/$defs/ByteSize" },
                        "zeroIsNull": { "type": "boolean", "default": false }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "lengthPolicy"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "BlobElement" },
                        "lengthPolicy": { "$ref": "#/$defs/LengthPolicy" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "lengthPolicy"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "StringElement" },
                        "lengthPolicy": { "$ref": "#/$defs/LengthPolicy" },
                        "charset": { "type": "string", "default": "UTF-8" },
                        "stopAtNull": { "type":  "boolean", "default": false }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "lengthPolicy", "schema"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ArrayElement" },
                        "lengthPolicy": { "$ref": "#/$defs/LengthPolicy" },
                        "schema": { "$ref": "#/$defs/SchemaElement" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "variables"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ComputedIntElement" },
                        "variables": {
                            "type": "array",
                            "minItems": 1,
                            "items": { "type": "string" }
                        },
                        "expression": { "$ref": "#/$defs/Expression" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "format", "variables"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ComputedStringFormatElement" },
                        "format": { "type": "string" },
                        "variables": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "minItems": 1,
                                "items": { "type": "string" }
                            }
                        }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "size"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "IntElement" },
                        "size": { "$ref": "#/$defs/LongByteSize" },
                        "signed": { "type": "boolean", "default": false },
                        "expression": { "$ref": "#/$defs/Expression" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "encoding"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "DynamicSizeIntElement" },
                        "encoding": {
                            "type": "string",
                            "enum": [ "ULEB128" ]
                        }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "BoolElement" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "size"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "FloatElement" },
                        "size": { "$ref": "#/$defs/LongByteSize" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "name"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "TypeElement" },
                        "name": { "type": "string" }
                    }
                }
            ]
        },
        "Classifier": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["@type", "enumClassifierName"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "EnumClassifier" },
                        "enumClassifierName": { "type": "string" },
                        "overrideBindings": { "type": "object", "$ref": "#/$defs/Bindings", "default": [] }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "size", "bindings"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "SelfEnumClassifier" },
                        "size": { "$ref": "#/$defs/ByteSize" },
                        "bindings": { "type": "object", "$ref": "#/$defs/Bindings" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "size", "rangeBindings"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "IntRangeClassifier" },
                        "size": { "$ref": "#/$defs/ByteSize" },
                        "rangeBindings": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["name", "from", "to"],
                                "properties": {
                                    "name": { "type": "string" },
                                    "from": { "$ref": "#/$defs/Decimal" },
                                    "to": { "$ref": "#/$defs/Decimal" }
                                }
                            }
                        }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "variable", "size"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ArrayStringRefClassifier" },
                        "variable": { "type": "string" },
                        "size": { "$ref": "#/$defs/ByteSize" },
                        "zeroIsNull": { "type": "boolean", "default": false }
                    }
                }
            ]
        },
        "LengthPolicy": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["@type", "length"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "FixedLengthPolicy" },
                        "length": { "$ref": "#/$defs/Decimal" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "fieldSize"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "PrefixedLengthPolicy" },
                        "fieldSize": { "$ref": "#/$defs/ByteSize" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "sizeVarName"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "ReferencedLengthPolicy" },
                        "sizeVarName": { "type": "string" }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type", "against", "operator"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "PredicateTerminatedPolicy" },
                        "structField": { "type": "string", "default": null },
                        "against": { "$ref": "#/$defs/Decimal" },
                        "operator": { "type": "string", "enum": ["EQUALS", "NOT_EQUALS", "LESS_THAN", "LESS_THAN_OR_EQUALS", "MORE_THAN", "MORE_THAN_OR_EQUALS"] }
                    }
                },
                {
                    "type": "object",
                    "required": ["@type"],
                    "additionalProperties": false,
                    "properties": {
                        "@type": { "const": "NullTerminatedStringPolicy" }
                    }
                }
            ]
        },
        "Bindings": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["key", "value"],
                "additionalProperties": false,
                "properties": {
                    "key": { "$ref": "#/$defs/Decimal" },
                    "value": { "type": "string" }
                }
            }
        },
        "Decimal": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string",
                    "pattern": "^(0x[0-9A-F]{1,16})|(0b[01]{1,64})|('.')$"
                }
            ]
        },
        "ByteSize": {
            "oneOf": [
                { "const": 1 },
                { "const": 2 },
                { "const": 4 }
            ]
        },
        "LongByteSize": {
            "oneOf": [
                { "const": 1 },
                { "const": 2 },
                { "const": 4 },
                { "const": 8 }
            ]
        },
        "Expression": {
            "type": "string",
            "pattern": "^(\\w+|\\d+|[+\\-*\/%])( (\\w+|\\d+|[+\\-*\/%]))*$"
        }
    }
}

=== Alathreon/AlaHexEditor/alahex_converted_schema.json
{
  "$schema": "https://raw.githubusercontent.com/Alathreon/AlaHexEditor/refs/heads/master/src/main/resources/alahex.schema.json",
  "references": [],
  "endianness": "LITTLE",
  "types": {
        "PacketID": {
      "@type": "EnumType",
      "size": 2,
      "constants": [
        { "key": 0, "value": "MSG_HEAD" },
        { "key": 1, "value": "MSG_SYS_reserve01" },
        { "key": 2, "value": "MSG_SYS_reserve02" },
        { "key": 3, "value": "MSG_SYS_reserve03" },
        { "key": 4, "value": "MSG_SYS_reserve04" },
        { "key": 5, "value": "MSG_SYS_reserve05" },
        { "key": 6, "value": "MSG_SYS_reserve06" },
        { "key": 7, "value": "MSG_SYS_reserve07" },
        { "key": 8, "value": "MSG_SYS_ADD_OBJECT" },
        { "key": 9, "value": "MSG_SYS_DEL_OBJECT" },
        { "key": 10, "value": "MSG_SYS_DISP_OBJECT" },
        { "key": 11, "value": "MSG_SYS_HIDE_OBJECT" },
        { "key": 12, "value": "MSG_SYS_reserve0C" },
        { "key": 13, "value": "MSG_SYS_reserve0D" },
        { "key": 14, "value": "MSG_SYS_reserve0E" },
        { "key": 15, "value": "MSG_SYS_EXTEND_THRESHOLD" },
        { "key": 16, "value": "MSG_SYS_END" },
        { "key": 17, "value": "MSG_SYS_NOP" },
        { "key": 18, "value": "MSG_SYS_ACK" },
        { "key": 19, "value": "MSG_SYS_TERMINAL_LOG" },
        { "key": 20, "value": "MSG_SYS_LOGIN" },
        { "key": 21, "value": "MSG_SYS_LOGOUT" },
        { "key": 22, "value": "MSG_SYS_SET_STATUS" },
        { "key": 23, "value": "MSG_SYS_PING" },
        { "key": 24, "value": "MSG_SYS_CAST_BINARY" },
        { "key": 25, "value": "MSG_SYS_HIDE_CLIENT" },
        { "key": 26, "value": "MSG_SYS_TIME" },
        { "key": 27, "value": "MSG_SYS_CASTED_BINARY" },
        { "key": 28, "value": "MSG_SYS_GET_FILE" },
        { "key": 29, "value": "MSG_SYS_ISSUE_LOGKEY" },
        { "key": 30, "value": "MSG_SYS_RECORD_LOG" },
        { "key": 31, "value": "MSG_SYS_ECHO" },
        { "key": 32, "value": "MSG_SYS_CREATE_STAGE" },
        { "key": 33, "value": "MSG_SYS_STAGE_DESTRUCT" },
        { "key": 34, "value": "MSG_SYS_ENTER_STAGE" },
        { "key": 35, "value": "MSG_SYS_BACK_STAGE" },
        { "key": 36, "value": "MSG_SYS_MOVE_STAGE" },
        { "key": 37, "value": "MSG_SYS_LEAVE_STAGE" },
        { "key": 38, "value": "MSG_SYS_LOCK_STAGE" },
        { "key": 39, "value": "MSG_SYS_UNLOCK_STAGE" },
        { "key": 40, "value": "MSG_SYS_RESERVE_STAGE" },
        { "key": 41, "value": "MSG_SYS_UNRESERVE_STAGE" },
        { "key": 42, "value": "MSG_SYS_SET_STAGE_PASS" },
        { "key": 43, "value": "MSG_SYS_WAIT_STAGE_BINARY" },
        { "key": 44, "value": "MSG_SYS_SET_STAGE_BINARY" },
        { "key": 45, "value": "MSG_SYS_GET_STAGE_BINARY" },
        { "key": 46, "value": "MSG_SYS_ENUMERATE_CLIENT" },
        { "key": 47, "value": "MSG_SYS_ENUMERATE_STAGE" },
        { "key": 48, "value": "MSG_SYS_CREATE_MUTEX" },
        { "key": 49, "value": "MSG_SYS_CREATE_OPEN_MUTEX" },
        { "key": 50, "value": "MSG_SYS_DELETE_MUTEX" },
        { "key": 51, "value": "MSG_SYS_OPEN_MUTEX" },
        { "key": 52, "value": "MSG_SYS_CLOSE_MUTEX" },
        { "key": 53, "value": "MSG_SYS_CREATE_SEMAPHORE" },
        { "key": 54, "value": "MSG_SYS_CREATE_ACQUIRE_SEMAPHORE" },
        { "key": 55, "value": "MSG_SYS_DELETE_SEMAPHORE" },
        { "key": 56, "value": "MSG_SYS_ACQUIRE_SEMAPHORE" },
        { "key": 57, "value": "MSG_SYS_RELEASE_SEMAPHORE" },
        { "key": 58, "value": "MSG_SYS_LOCK_GLOBAL_SEMA" },
        { "key": 59, "value": "MSG_SYS_UNLOCK_GLOBAL_SEMA" },
        { "key": 60, "value": "MSG_SYS_CHECK_SEMAPHORE" },
        { "key": 61, "value": "MSG_SYS_OPERATE_REGISTER" },
        { "key": 62, "value": "MSG_SYS_LOAD_REGISTER" },
        { "key": 63, "value": "MSG_SYS_NOTIFY_REGISTER" },
        { "key": 64, "value": "MSG_SYS_CREATE_OBJECT" },
        { "key": 65, "value": "MSG_SYS_DELETE_OBJECT" },
        { "key": 66, "value": "MSG_SYS_POSITION_OBJECT" },
        { "key": 67, "value": "MSG_SYS_ROTATE_OBJECT" },
        { "key": 68, "value": "MSG_SYS_DUPLICATE_OBJECT" },
        { "key": 69, "value": "MSG_SYS_SET_OBJECT_BINARY" },
        { "key": 70, "value": "MSG_SYS_GET_OBJECT_BINARY" },
        { "key": 71, "value": "MSG_SYS_GET_OBJECT_OWNER" },
        { "key": 72, "value": "MSG_SYS_UPDATE_OBJECT_BINARY" },
        { "key": 73, "value": "MSG_SYS_CLEANUP_OBJECT" },
        { "key": 74, "value": "MSG_SYS_reserve4A" },
        { "key": 75, "value": "MSG_SYS_reserve4B" },
        { "key": 76, "value": "MSG_SYS_reserve4C" },
        { "key": 77, "value": "MSG_SYS_reserve4D" },
        { "key": 78, "value": "MSG_SYS_reserve4E" },
        { "key": 79, "value": "MSG_SYS_reserve4F" },
        { "key": 80, "value": "MSG_SYS_INSERT_USER" },
        { "key": 81, "value": "MSG_SYS_DELETE_USER" },
        { "key": 82, "value": "MSG_SYS_SET_USER_BINARY" },
        { "key": 83, "value": "MSG_SYS_GET_USER_BINARY" },
        { "key": 84, "value": "MSG_SYS_NOTIFY_USER_BINARY" },
        { "key": 85, "value": "MSG_SYS_reserve55" },
        { "key": 86, "value": "MSG_SYS_reserve56" },
        { "key": 87, "value": "MSG_SYS_reserve57" },
        { "key": 88, "value": "MSG_SYS_UPDATE_RIGHT" },
        { "key": 89, "value": "MSG_SYS_AUTH_QUERY" },
        { "key": 90, "value": "MSG_SYS_AUTH_DATA" },
        { "key": 91, "value": "MSG_SYS_AUTH_TERMINAL" },
        { "key": 92, "value": "MSG_SYS_reserve5C" },
        { "key": 93, "value": "MSG_SYS_RIGHTS_RELOAD" },
        { "key": 94, "value": "MSG_SYS_reserve5E" },
        { "key": 95, "value": "MSG_SYS_reserve5F" },
        { "key": 96, "value": "MSG_MHF_SAVEDATA" },
        { "key": 97, "value": "MSG_MHF_LOADDATA" },
        { "key": 98, "value": "MSG_MHF_LIST_MEMBER" },
        { "key": 99, "value": "MSG_MHF_OPR_MEMBER" },
        { "key": 100, "value": "MSG_MHF_ENUMERATE_DIST_ITEM" },
        { "key": 101, "value": "MSG_MHF_APPLY_DIST_ITEM" },
        { "key": 102, "value": "MSG_MHF_ACQUIRE_DIST_ITEM" },
        { "key": 103, "value": "MSG_MHF_GET_DIST_DESCRIPTION" },
        { "key": 104, "value": "MSG_MHF_SEND_MAIL" },
        { "key": 105, "value": "MSG_MHF_READ_MAIL" },
        { "key": 106, "value": "MSG_MHF_LIST_MAIL" },
        { "key": 107, "value": "MSG_MHF_OPRT_MAIL" },
        { "key": 108, "value": "MSG_MHF_LOAD_FAVORITE_QUEST" },
        { "key": 109, "value": "MSG_MHF_SAVE_FAVORITE_QUEST" },
        { "key": 110, "value": "MSG_MHF_REGISTER_EVENT" },
        { "key": 111, "value": "MSG_MHF_RELEASE_EVENT" },
        { "key": 112, "value": "MSG_MHF_TRANSIT_MESSAGE" },
        { "key": 113, "value": "MSG_SYS_reserve71" },
        { "key": 114, "value": "MSG_SYS_reserve72" },
        { "key": 115, "value": "MSG_SYS_reserve73" },
        { "key": 116, "value": "MSG_SYS_reserve74" },
        { "key": 117, "value": "MSG_SYS_reserve75" },
        { "key": 118, "value": "MSG_SYS_reserve76" },
        { "key": 119, "value": "MSG_SYS_reserve77" },
        { "key": 120, "value": "MSG_SYS_reserve78" },
        { "key": 121, "value": "MSG_SYS_reserve79" },
        { "key": 122, "value": "MSG_SYS_reserve7A" },
        { "key": 123, "value": "MSG_SYS_reserve7B" },
        { "key": 124, "value": "MSG_SYS_reserve7C" },
        { "key": 125, "value": "MSG_CA_EXCHANGE_ITEM" },
        { "key": 126, "value": "MSG_SYS_reserve7E" },
        { "key": 127, "value": "MSG_MHF_PRESENT_BOX" },
        { "key": 128, "value": "MSG_MHF_SERVER_COMMAND" },
        { "key": 129, "value": "MSG_MHF_SHUT_CLIENT" },
        { "key": 130, "value": "MSG_MHF_ANNOUNCE" },
        { "key": 131, "value": "MSG_MHF_SET_LOGINWINDOW" },
        { "key": 132, "value": "MSG_SYS_TRANS_BINARY" },
        { "key": 133, "value": "MSG_SYS_COLLECT_BINARY" },
        { "key": 134, "value": "MSG_SYS_GET_STATE" },
        { "key": 135, "value": "MSG_SYS_SERIALIZE" },
        { "key": 136, "value": "MSG_SYS_ENUMLOBBY" },
        { "key": 137, "value": "MSG_SYS_ENUMUSER" },
        { "key": 138, "value": "MSG_SYS_INFOKYSERVER" },
        { "key": 139, "value": "MSG_MHF_GET_CA_UNIQUE_ID" },
        { "key": 140, "value": "MSG_MHF_SET_CA_ACHIEVEMENT" },
        { "key": 141, "value": "MSG_MHF_CARAVAN_MY_SCORE" },
        { "key": 142, "value": "MSG_MHF_CARAVAN_RANKING" },
        { "key": 143, "value": "MSG_MHF_CARAVAN_MY_RANK" },
        { "key": 144, "value": "MSG_MHF_CREATE_GUILD" },
        { "key": 145, "value": "MSG_MHF_OPERATE_GUILD" },
        { "key": 146, "value": "MSG_MHF_OPERATE_GUILD_MEMBER" },
        { "key": 147, "value": "MSG_MHF_INFO_GUILD" },
        { "key": 148, "value": "MSG_MHF_ENUMERATE_GUILD" },
        { "key": 149, "value": "MSG_MHF_UPDATE_GUILD" },
        { "key": 150, "value": "MSG_MHF_ARRANGE_GUILD_MEMBER" },
        { "key": 151, "value": "MSG_MHF_ENUMERATE_GUILD_MEMBER" },
        { "key": 152, "value": "MSG_MHF_ENUMERATE_CAMPAIGN" },
        { "key": 153, "value": "MSG_MHF_STATE_CAMPAIGN" },
        { "key": 154, "value": "MSG_MHF_APPLY_CAMPAIGN" },
        { "key": 155, "value": "MSG_MHF_ENUMERATE_ITEM" },
        { "key": 156, "value": "MSG_MHF_ACQUIRE_ITEM" },
        { "key": 157, "value": "MSG_MHF_TRANSFER_ITEM" },
        { "key": 158, "value": "MSG_MHF_MERCENARY_HUNTDATA" },
        { "key": 159, "value": "MSG_MHF_ENTRY_ROOKIE_GUILD" },
        { "key": 160, "value": "MSG_MHF_ENUMERATE_QUEST" },
        { "key": 161, "value": "MSG_MHF_ENUMERATE_EVENT" },
        { "key": 162, "value": "MSG_MHF_ENUMERATE_PRICE" },
        { "key": 163, "value": "MSG_MHF_ENUMERATE_RANKING" },
        { "key": 164, "value": "MSG_MHF_ENUMERATE_ORDER" },
        { "key": 165, "value": "MSG_MHF_ENUMERATE_SHOP" },
        { "key": 166, "value": "MSG_MHF_GET_EXTRA_INFO" },
        { "key": 167, "value": "MSG_MHF_UPDATE_INTERIOR" },
        { "key": 168, "value": "MSG_MHF_ENUMERATE_HOUSE" },
        { "key": 169, "value": "MSG_MHF_UPDATE_HOUSE" },
        { "key": 170, "value": "MSG_MHF_LOAD_HOUSE" },
